### ISSUE TITLE
alt-u doesn't work on Mac OS X

### ISSUE THREAD

**Issue by srki80** [ThomasGoris/CheckMate#5]
It appears that on Mac OS X Sierra (10.12.3) alt+u is bound to an umlaut ¨ character. I suggest using a different keybinding for Mac OS X if possible. 

I'll see if there's a way to disable alt+u umlaut as temporary workaround.

**Comment by ThomasGoris** [comment]
I didn't even consider the default Mac OS X key bindings. 
For the moment you can change the keybind by going to settings > keymap > find checkmate. 

I'll try to find a keybind that is applicable to Mac, Windows and Linux and add it to the new version.

**Comment by srki80** [comment]
Thanks. shift+alt+u seems to be free an it's working fine.

**Comment by ThomasGoris** [comment]
I added shift+alt+u as the default keybinding for Mac OS X. 
I kept alt+u as the windows keybinding to avoid confusion after the update. 
The update has been scheduled to happen within two days. 

Thanks for helping me fix this issue.
